MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH_T: 'jx_vit_base_p16_224-80ecf9dd.pth'
  TRANSFORMER_TYPE: 'vit_base_patch16_224'
  STRIDE_SIZE: [ 16, 16 ]
  SIE_CAMERA: True
  RE: 1
  # DEVICE_ID: '1'
  RE_LAYER: 1
  DIRECT: 1 # We find that for vehicle reid, indirect is better than direct
INPUT:
  SIZE_TRAIN: [128,256] # For VehicleID, you can also use [128,256], we simply use the same setting as Person-ReID
  SIZE_TEST: [128,256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
DATALOADER:
  SAMPLER: 'softmax_triplet'

DATASETS:
  NAMES: ('MSVR310')
  ROOT_DIR: ''

SOLVER:
  MAX_EPOCHS: 1000 # Here we follow the setting CCNet
  BASE_LR: 0.001   # Here we use a smaller learning rate
  WARMUP_ITERS: 100

TEST:
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  MISS: 'nothing'

OUTPUT_DIR: './MSVR310/TOP-ReID'

